# Generated by Django 6.0 on 2025-12-09 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0002_alter_board_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assignee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reviewer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
